// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwKJBTvI0HYYaVk-iBa7u5UVKcX8hV1-M',
    appId: '1:981802355757:web:1ffbf30f8e4ec69cbafca4',
    messagingSenderId: '981802355757',
    projectId: 'flutter-firebase-app-c3e77',
    authDomain: 'flutter-firebase-app-c3e77.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-c3e77.firebasestorage.app',
    measurementId: 'G-9GXYZ04JJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmFcDZwtvop1Pbu-RnLQZOBAYMIDsHEkU',
    appId: '1:981802355757:android:8e5dd7e9c4ea4c47bafca4',
    messagingSenderId: '981802355757',
    projectId: 'flutter-firebase-app-c3e77',
    storageBucket: 'flutter-firebase-app-c3e77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_SnkXZUGLkHCRzvWzpGvSCFlAQPi0XfU',
    appId: '1:981802355757:ios:1f27124d11523275bafca4',
    messagingSenderId: '981802355757',
    projectId: 'flutter-firebase-app-c3e77',
    storageBucket: 'flutter-firebase-app-c3e77.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_SnkXZUGLkHCRzvWzpGvSCFlAQPi0XfU',
    appId: '1:981802355757:ios:1f27124d11523275bafca4',
    messagingSenderId: '981802355757',
    projectId: 'flutter-firebase-app-c3e77',
    storageBucket: 'flutter-firebase-app-c3e77.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwKJBTvI0HYYaVk-iBa7u5UVKcX8hV1-M',
    appId: '1:981802355757:web:11a6a052ba4e6464bafca4',
    messagingSenderId: '981802355757',
    projectId: 'flutter-firebase-app-c3e77',
    authDomain: 'flutter-firebase-app-c3e77.firebaseapp.com',
    storageBucket: 'flutter-firebase-app-c3e77.firebasestorage.app',
    measurementId: 'G-VE4DYJYBKR',
  );
}
